title: Documentation of Open Design Lab Textile 2025 
description: Learning, making and exhibiting machine-assisted design of textile arts and crafts from BUDA::lab (Kortrijk, Belgium)
theme: jekyll-theme-modernist
